import { NextResponse } from 'next/server'

export async function GET() {
  const scan = {
    generatedAt: new Date().toISOString(),
    pageRoutes: [
      { path: '/', file: 'src/app/page.tsx', description: 'Dashboard — active tasks, agent status overview' },
      { path: '/login', file: 'src/app/login/page.tsx', description: 'Login page with email/password auth' },
      { path: '/tasks', file: 'src/app/tasks/page.tsx', description: 'Task board — 5-column kanban (Inbox, Assigned, In Progress, Review, Done)' },
      { path: '/tasks/[id]', file: 'src/app/tasks/[id]/page.tsx', description: 'Task detail page with activity log' },
      { path: '/clients', file: 'src/app/clients/page.tsx', description: 'Client list with search and status filtering' },
      { path: '/clients/[id]', file: 'src/app/clients/[id]/page.tsx', description: 'Client detail — tabs: Overview, Websites, Services, Notes, Links' },
      { path: '/websites', file: 'src/app/websites/page.tsx', description: 'All websites overview with status filtering' },
      { path: '/seo/[websiteId]', file: 'src/app/seo/[websiteId]/page.tsx', description: 'SEO dashboard — page auditing, AI meta tag generation' },
      { path: '/agents', file: 'src/app/agents/page.tsx', description: 'Agent roster — all agents with operational status' },
      { path: '/revenue', file: 'src/app/revenue/page.tsx', description: 'Revenue analytics — MRR, service breakdown, top clients' },
    ],
    apiRoutes: [
      { path: '/api/auth/[...nextauth]', methods: ['GET', 'POST'], description: 'NextAuth.js credentials provider' },
      { path: '/api/tasks', methods: ['GET', 'POST'], description: 'List all tasks / Create task' },
      { path: '/api/tasks/[id]', methods: ['GET', 'PATCH', 'DELETE'], description: 'Get / Update / Delete task' },
      { path: '/api/tasks/[id]/execute', methods: ['POST'], description: 'Execute task with assigned agent' },
      { path: '/api/tasks/[id]/status', methods: ['GET'], description: 'Get task status and activities' },
      { path: '/api/clients', methods: ['GET', 'POST'], description: 'List clients (search, filter) / Create client' },
      { path: '/api/clients/[id]', methods: ['GET', 'PATCH'], description: 'Get / Update client details' },
      { path: '/api/clients/[id]/notes', methods: ['GET', 'POST'], description: 'List / Add client notes' },
      { path: '/api/clients/[id]/services', methods: ['GET', 'POST'], description: 'List / Add client services' },
      { path: '/api/clients/[id]/links', methods: ['GET', 'POST'], description: 'List / Add client portal links' },
      { path: '/api/websites', methods: ['GET', 'POST'], description: 'List websites (filter by status) / Create website' },
      { path: '/api/websites/[id]', methods: ['GET', 'PATCH'], description: 'Get / Update website details' },
      { path: '/api/websites/[id]/seo', methods: ['GET', 'POST', 'PATCH'], description: 'SEO pages — list, add, update' },
      { path: '/api/seo/audit', methods: ['POST'], description: 'Run full website SEO audit' },
      { path: '/api/seo/generate-meta', methods: ['POST'], description: 'AI-generated meta tags' },
      { path: '/api/seo/suggest-keywords', methods: ['POST'], description: 'AI keyword suggestions' },
      { path: '/api/seo/rewrite', methods: ['POST'], description: 'AI content rewriting' },
      { path: '/api/agents', methods: ['GET'], description: 'List all agents' },
      { path: '/api/agents/openclaw-status', methods: ['GET'], description: 'OpenClaw local execution availability' },
      { path: '/api/revenue', methods: ['GET'], description: 'Revenue analytics — MRR, projections, breakdowns' },
      { path: '/api/services', methods: ['GET'], description: 'List all services' },
      { path: '/api/workflows', methods: ['GET'], description: 'List workflow templates' },
      { path: '/api/app-scan', methods: ['GET'], description: 'This endpoint — app structure summary' },
    ],
    components: [
      { name: 'Sidebar', file: 'src/components/Sidebar.tsx', description: 'Fixed left sidebar with nav links and user profile' },
      { name: 'SessionWrapper', file: 'src/components/SessionWrapper.tsx', description: 'NextAuth SessionProvider wrapper' },
      { name: 'TaskBoard', file: 'src/components/TaskBoard.tsx', description: '5-column kanban board' },
      { name: 'TaskCard', file: 'src/components/TaskCard.tsx', description: 'Task card with status, agent, priority display' },
      { name: 'CreateTaskModal', file: 'src/components/CreateTaskModal.tsx', description: 'Modal for creating tasks with client/agent/workflow selection' },
      { name: 'AgentCard', file: 'src/components/AgentCard.tsx', description: 'Agent status card — name, role, status, model' },
    ],
    databaseSchema: {
      provider: 'postgresql',
      models: [
        {
          name: 'Task',
          table: 'tasks',
          columns: [
            { name: 'id', type: 'String', attributes: 'PK, UUID' },
            { name: 'title', type: 'String', attributes: 'required' },
            { name: 'description', type: 'String', attributes: 'optional' },
            { name: 'status', type: 'String', attributes: 'default: inbox' },
            { name: 'priority', type: 'String', attributes: 'default: normal' },
            { name: 'assignedAgentId', type: 'String', attributes: 'optional, FK -> agents' },
            { name: 'workflowTemplateId', type: 'String', attributes: 'optional' },
            { name: 'createdAt', type: 'DateTime', attributes: 'auto' },
            { name: 'updatedAt', type: 'DateTime', attributes: 'auto' },
            { name: 'dueDate', type: 'DateTime', attributes: 'optional' },
            { name: 'workspaceId', type: 'String', attributes: 'optional' },
            { name: 'deliverables', type: 'String', attributes: 'default: []' },
            { name: 'sessionKey', type: 'String', attributes: 'optional' },
            { name: 'parentTaskId', type: 'String', attributes: 'optional' },
            { name: 'clientId', type: 'String', attributes: 'optional, FK -> clients' },
          ],
          relations: ['Activity[] (activities)', 'Client? (client)'],
        },
        {
          name: 'Agent',
          table: 'agents',
          columns: [
            { name: 'id', type: 'String', attributes: 'PK' },
            { name: 'name', type: 'String', attributes: 'required' },
            { name: 'role', type: 'String', attributes: 'required' },
            { name: 'description', type: 'String', attributes: 'optional' },
            { name: 'soulMd', type: 'String', attributes: 'optional' },
            { name: 'model', type: 'String', attributes: 'optional' },
            { name: 'status', type: 'String', attributes: 'default: standby' },
            { name: 'workspaceId', type: 'String', attributes: 'optional' },
            { name: 'createdAt', type: 'DateTime', attributes: 'auto' },
          ],
          relations: ['Activity[] (activities)'],
        },
        {
          name: 'WorkflowTemplate',
          table: 'workflow_templates',
          columns: [
            { name: 'id', type: 'String', attributes: 'PK' },
            { name: 'name', type: 'String', attributes: 'required' },
            { name: 'description', type: 'String', attributes: 'optional' },
            { name: 'stages', type: 'String', attributes: 'required (JSON)' },
            { name: 'workspaceId', type: 'String', attributes: 'optional' },
          ],
          relations: [],
        },
        {
          name: 'Activity',
          table: 'activities',
          columns: [
            { name: 'id', type: 'String', attributes: 'PK, UUID' },
            { name: 'taskId', type: 'String', attributes: 'optional, FK -> tasks' },
            { name: 'agentId', type: 'String', attributes: 'optional, FK -> agents' },
            { name: 'activityType', type: 'String', attributes: 'required' },
            { name: 'content', type: 'String', attributes: 'optional' },
            { name: 'createdAt', type: 'DateTime', attributes: 'auto' },
          ],
          relations: ['Task? (task)', 'Agent? (agent)'],
        },
        {
          name: 'User',
          table: 'users',
          columns: [
            { name: 'id', type: 'String', attributes: 'PK, UUID' },
            { name: 'name', type: 'String', attributes: 'optional' },
            { name: 'email', type: 'String', attributes: 'required, unique' },
            { name: 'password', type: 'String', attributes: 'required' },
            { name: 'role', type: 'String', attributes: 'default: user' },
            { name: 'createdAt', type: 'DateTime', attributes: 'auto' },
          ],
          relations: ['Session[] (sessions)'],
        },
        {
          name: 'Session',
          table: 'sessions',
          columns: [
            { name: 'id', type: 'String', attributes: 'PK, UUID' },
            { name: 'userId', type: 'String', attributes: 'required, FK -> users' },
            { name: 'token', type: 'String', attributes: 'required, unique' },
            { name: 'expiresAt', type: 'DateTime', attributes: 'required' },
          ],
          relations: ['User (user)'],
        },
        {
          name: 'Client',
          table: 'clients',
          columns: [
            { name: 'id', type: 'String', attributes: 'PK, UUID' },
            { name: 'businessName', type: 'String', attributes: 'required' },
            { name: 'contactName', type: 'String', attributes: 'optional' },
            { name: 'email', type: 'String', attributes: 'optional' },
            { name: 'phone', type: 'String', attributes: 'optional' },
            { name: 'businessType', type: 'String', attributes: 'optional' },
            { name: 'city', type: 'String', attributes: 'optional' },
            { name: 'state', type: 'String', attributes: 'optional' },
            { name: 'status', type: 'String', attributes: 'default: lead' },
            { name: 'monthlyRevenue', type: 'Float', attributes: 'optional' },
            { name: 'dateAcquired', type: 'DateTime', attributes: 'optional' },
            { name: 'tags', type: 'String', attributes: 'optional (JSON array)' },
            { name: 'createdAt', type: 'DateTime', attributes: 'auto' },
            { name: 'updatedAt', type: 'DateTime', attributes: 'auto' },
          ],
          relations: ['ClientNote[] (notes)', 'Website[] (websites)', 'Service[] (services)', 'ClientLink[] (links)', 'Task[] (tasks)'],
        },
        {
          name: 'ClientNote',
          table: 'client_notes',
          columns: [
            { name: 'id', type: 'String', attributes: 'PK, UUID' },
            { name: 'clientId', type: 'String', attributes: 'required, FK -> clients' },
            { name: 'content', type: 'String', attributes: 'required' },
            { name: 'createdAt', type: 'DateTime', attributes: 'auto' },
          ],
          relations: ['Client (client, cascade delete)'],
        },
        {
          name: 'Website',
          table: 'websites',
          columns: [
            { name: 'id', type: 'String', attributes: 'PK, UUID' },
            { name: 'clientId', type: 'String', attributes: 'required, FK -> clients' },
            { name: 'url', type: 'String', attributes: 'required' },
            { name: 'status', type: 'String', attributes: 'default: development' },
            { name: 'hostingProvider', type: 'String', attributes: 'optional' },
            { name: 'domainRegistrar', type: 'String', attributes: 'optional' },
            { name: 'domainExpiration', type: 'DateTime', attributes: 'optional' },
            { name: 'sslStatus', type: 'String', attributes: 'optional' },
            { name: 'cmsPlatform', type: 'String', attributes: 'optional' },
            { name: 'launchDate', type: 'DateTime', attributes: 'optional' },
            { name: 'lastUpdated', type: 'DateTime', attributes: 'optional' },
            { name: 'gaConnected', type: 'Boolean', attributes: 'default: false' },
            { name: 'gaPropertyId', type: 'String', attributes: 'optional' },
            { name: 'gscConnected', type: 'Boolean', attributes: 'default: false' },
            { name: 'maintenancePlan', type: 'Boolean', attributes: 'default: false' },
            { name: 'maintenanceDetails', type: 'String', attributes: 'optional' },
            { name: 'notes', type: 'String', attributes: 'optional' },
            { name: 'createdAt', type: 'DateTime', attributes: 'auto' },
            { name: 'updatedAt', type: 'DateTime', attributes: 'auto' },
          ],
          relations: ['Client (client, cascade delete)', 'SeoPage[] (seoPages)'],
        },
        {
          name: 'SeoPage',
          table: 'seo_pages',
          columns: [
            { name: 'id', type: 'String', attributes: 'PK, UUID' },
            { name: 'websiteId', type: 'String', attributes: 'required, FK -> websites' },
            { name: 'pageUrl', type: 'String', attributes: 'required' },
            { name: 'pageTitle', type: 'String', attributes: 'optional' },
            { name: 'titleLength', type: 'Int', attributes: 'optional' },
            { name: 'metaDescription', type: 'String', attributes: 'optional' },
            { name: 'metaDescLength', type: 'Int', attributes: 'optional' },
            { name: 'h1Tag', type: 'String', attributes: 'optional' },
            { name: 'h1Count', type: 'Int', attributes: 'optional' },
            { name: 'headingStructure', type: 'String', attributes: 'optional (JSON)' },
            { name: 'imagesTotal', type: 'Int', attributes: 'optional' },
            { name: 'imagesWithAlt', type: 'Int', attributes: 'optional' },
            { name: 'internalLinks', type: 'Int', attributes: 'optional' },
            { name: 'externalLinks', type: 'Int', attributes: 'optional' },
            { name: 'wordCount', type: 'Int', attributes: 'optional' },
            { name: 'targetKeyword', type: 'String', attributes: 'optional' },
            { name: 'keywordDensity', type: 'Float', attributes: 'optional' },
            { name: 'seoScore', type: 'Int', attributes: 'optional' },
            { name: 'lastAudited', type: 'DateTime', attributes: 'optional' },
            { name: 'createdAt', type: 'DateTime', attributes: 'auto' },
            { name: 'updatedAt', type: 'DateTime', attributes: 'auto' },
          ],
          relations: ['Website (website, cascade delete)', 'SeoChange[] (changes)'],
        },
        {
          name: 'SeoChange',
          table: 'seo_changes',
          columns: [
            { name: 'id', type: 'String', attributes: 'PK, UUID' },
            { name: 'seoPageId', type: 'String', attributes: 'required, FK -> seo_pages' },
            { name: 'fieldChanged', type: 'String', attributes: 'optional' },
            { name: 'oldValue', type: 'String', attributes: 'optional' },
            { name: 'newValue', type: 'String', attributes: 'optional' },
            { name: 'changedBy', type: 'String', attributes: 'optional' },
            { name: 'createdAt', type: 'DateTime', attributes: 'auto' },
          ],
          relations: ['SeoPage (seoPage, cascade delete)'],
        },
        {
          name: 'Service',
          table: 'services',
          columns: [
            { name: 'id', type: 'String', attributes: 'PK, UUID' },
            { name: 'clientId', type: 'String', attributes: 'required, FK -> clients' },
            { name: 'serviceType', type: 'String', attributes: 'required' },
            { name: 'status', type: 'String', attributes: 'default: active' },
            { name: 'billingType', type: 'String', attributes: 'optional' },
            { name: 'price', type: 'Float', attributes: 'optional' },
            { name: 'startDate', type: 'DateTime', attributes: 'optional' },
            { name: 'nextBillingDate', type: 'DateTime', attributes: 'optional' },
            { name: 'notes', type: 'String', attributes: 'optional' },
            { name: 'createdAt', type: 'DateTime', attributes: 'auto' },
            { name: 'updatedAt', type: 'DateTime', attributes: 'auto' },
          ],
          relations: ['Client (client, cascade delete)'],
        },
        {
          name: 'ClientLink',
          table: 'client_links',
          columns: [
            { name: 'id', type: 'String', attributes: 'PK, UUID' },
            { name: 'clientId', type: 'String', attributes: 'required, FK -> clients' },
            { name: 'category', type: 'String', attributes: 'optional' },
            { name: 'label', type: 'String', attributes: 'required' },
            { name: 'url', type: 'String', attributes: 'optional' },
            { name: 'username', type: 'String', attributes: 'optional' },
            { name: 'password', type: 'String', attributes: 'optional' },
            { name: 'notes', type: 'String', attributes: 'optional' },
            { name: 'createdAt', type: 'DateTime', attributes: 'auto' },
          ],
          relations: ['Client (client, cascade delete)'],
        },
      ],
    },
    navigation: {
      type: 'Fixed left sidebar',
      component: 'src/components/Sidebar.tsx',
      items: [
        { label: 'Dashboard', path: '/', icon: 'LayoutDashboard' },
        { label: 'Tasks', path: '/tasks', icon: 'CheckSquare' },
        { label: 'Clients', path: '/clients', icon: 'Users' },
        { label: 'Websites', path: '/websites', icon: 'Globe' },
        { label: 'Revenue', path: '/revenue', icon: 'DollarSign' },
        { label: 'Agents', path: '/agents', icon: 'Bot' },
      ],
      auth: 'NextAuth.js with credentials provider, session indicator in sidebar footer',
    },
    techStack: {
      framework: 'Next.js (App Router)',
      database: 'PostgreSQL via Prisma ORM',
      auth: 'NextAuth.js (credentials provider)',
      ai: 'Anthropic Claude API',
      localExecution: 'OpenClaw',
      styling: 'Tailwind CSS + Geist font',
    },
  }

  return NextResponse.json(scan, { status: 200 })
}
